{{- if .Values.classificationCatalogEnabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: classification-catalog
  namespace: {{ .Release.Namespace }}
data:
  classifications.json: |-
    {{- include "hub.classificationCatalog" . | nindent 4 }}
{{- end }}