{{- if and (or (eq .Values.mode "all") (eq .Values.mode "ui")) .Values.kerberoshub.auditDispatcher.enabled .Values.kerberoshub.auditDispatcher.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hub-audit-dispatcher-servicemonitor
  namespace: {{ .Release.Namespace }}
  labels:
    service: hub-audit-dispatcher
    release: prometheus
spec:
  selector:
    matchLabels:
      service: hub-audit-dispatcher
  endpoints:
    - port: metrics
      interval: {{ .Values.kerberoshub.auditDispatcher.serviceMonitor.interval }}
      path: /metrics
{{- end }}
