apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipe-dominantcolor
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.kerberospipeline.dominantColor.replicas }}
  selector:
    matchLabels:
      app: pipe-dominantcolor
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: pipe-dominantcolor
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: pipe-dominantcolor
        image: "{{ .Values.global.imageRegistry }}{{ .Values.kerberospipeline.dominantColor.repository }}:{{ .Values.kerberospipeline.dominantColor.tag }}"
        imagePullPolicy: {{ .Values.kerberospipeline.dominantColor.pullPolicy }}
        {{- with .Values.kerberospipeline.dominantColor.resources }}
        resources:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        env:
        - name: CLOUD_PROVIDER
          value: "{{ .Values.cloudProvider }}"
        - name: QUEUE_SYSTEM
          value: "{{ .Values.queueProvider }}"

        # Kafka settings
        - name: KAFKA_BROKER
          value: "{{ .Values.kafka.broker }}"
        - name: KAFKA_USERNAME
          value: "{{ .Values.kafka.username }}"
        - name: KAFKA_PASSWORD
          value: "{{ .Values.kafka.password }}"
        - name: KAFKA_MECHANISM
          value: "{{ .Values.kafka.mechanism }}"
        - name: KAFKA_SECURITY
          value: "{{ .Values.kafka.security }}"

        # RabbitMQ settings
        - name: RABBITMQ_HOST
          value: "{{ .Values.rabbitmq.host }}"
        - name: RABBITMQ_EXCHANGE
          value: "{{ .Values.rabbitmq.exchange }}"
        - name: RABBITMQ_USERNAME
          value: "{{ .Values.rabbitmq.username }}"
        - name: RABBITMQ_PASSWORD
          value: "{{ .Values.rabbitmq.password }}"
        
        # Open Telemetry tracing
        - name: OTEL_EXPORTED_OTLP_ENABLED
          value: "{{ .Values.opentelemetry.enabled }}"
        - name: OTEL_EXPORTED_OTLP_ROUTING_ENABLED
          value: "{{ .Values.opentelemetry.routingEnabled }}"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "{{ .Values.opentelemetry.collector.endpoint }}"
---
apiVersion: v1
kind: Service
metadata:
  name: pipe-dominantcolor
  namespace: {{ .Release.Namespace }}
  labels:
    app: pipe-dominantcolor
    service: pipe
spec:
  ports:
    - name: hub-metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: pipe-dominantcolor